name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build_and_deploy:
    runs-on: [self-hosted, windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t node-app .

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}  # Store your kubeconfig file as a secret

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml


        